spring:
  application:
    name: customer-management
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/